# Generated by Django 4.1.7 on 2023-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
