# Generated by Django 4.1.7 on 2023-03-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_menuitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='children',
            field=models.JSONField(null=True),
        ),
    ]
