# Generated by Django 4.1.7 on 2023-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_menuitem_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='children',
            field=models.JSONField(default={'child': []}),
        ),
    ]
