# Generated by Django 4.1.7 on 2023-03-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_menuitem_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
