# Generated by Django 4.1.7 on 2023-03-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_menuitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='children',
        ),
    ]
